### PR TITLE
added myProfile

### PR DESCRIPTION
**Pull request by garimajain12**
Added GarimaJainProfile #2

### CODE REVIEW

**Review by NS007-dev — COMMENTED** [review]
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊

**Review by NS007-dev — APPROVED** [review]

**Comment by garimajain12** [comment]
Why your project has been excluded?

**Comment by NS007-dev** [comment]
@garimajain12 this is not my project as I asked to have access to merge prs only. Unfortunately this project is no longer part of Hacktoberfest. I am sorry for this. Thank you.

**Comment by garimajain12** [comment]
Thankyou for the clarification.
But now i have to complete one progress to complete the hacktober fest
progress.
What should i do now?

**Comment by NS007-dev** [comment]
@garimajain12 this repo https://github.com/lucasgdb/useful-dev-tools

I contributed to is for hacktoberfest. Just give two resources for devs and it will be hacktoberfest accepted! Hope that helps. Need any more help or resources, feel free to ask. Thank you

**Pull request merged**
