### PR TITLE
hacktoberfest

### PR DESCRIPTION
**Pull request by Princekumaraj**
i am just adding new file

### CODE REVIEW

**Review by iamdevvalecha — CHANGES_REQUESTED** [review]
please follow #3

**Comment by iamdevvalecha** [comment]
@Princekumaraj - Star this repository
- [GitHub followers](https://github.com/iamdevvalecha/)

**Comment by Princekumaraj** [comment]
why u closed this pr without accepting it ?

**Comment by CodingSpecies** [comment]
@Princekumaraj you need to follow the readme and image rule : #2 thank you. Any help needed, feel free to ask.

**Comment by Princekumaraj** [comment]
can u now add my pr

**Comment by CodingSpecies** [comment]
@Princekumaraj #164

**Pull request closed without merging**
