### PR TITLE
improved readme

### PR DESCRIPTION
**Pull request by CodingSpecies**
Just fixed some errors, and added some more to the readme @iamdevvalecha .Thanks.

### CODE REVIEW

**Comment by CodingSpecies** [comment]
@iamdevvalecha I added on what to name pr as well. #16

**Review by iamdevvalecha — APPROVED** [review]
Captivating! thanks @CodingSpecies 💯

**Comment by CodingSpecies** [comment]
@iamdevvalecha as there is a high rise in pr's is it possible for me to be able to have access to adding labels, and merging pr's? if not it's ok. Thank you

**Comment by iamdevvalecha** [comment]
> @iamdevvalecha as there is a high rise in pr's is it possible for me to be able to have access to adding labels, and merging pr's? if not it's ok. Thank you
> 
> also when I review, does the format of the file matter?

sure! i will invite you as collabrator.

**Pull request merged**
